### ISSUE TITLE
Visualización de datos 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-j-a-k#1]
[Reporte 2 visualizacion de datos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-j-a-k/files/15445656/Reporte.2.visualizacion.de.datos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
